FROM node:16-slim

USER node

WORKDIR /app

#COPY package*.json ./
#RUN npm install

#FROM node:16
#WORKDIR /app
#COPY --from=build /app /app
#COPY . .

#EXPOSE 8686
#CMD ["node", "index.js"]